# Generated by Django 4.1.5 on 2024-05-18 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("locality", models.CharField(max_length=200)),
                ("city", models.CharField(max_length=50)),
                ("zipcode", models.IntegerField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("Andaman & Nincobar Island", "Andaman & Nincobar Island"),
                            ("Andhra Pradesh", "Andhra Pradesh"),
                            ("Assam", "Assam"),
                            ("Bihar", "Bihar"),
                            ("Chandigarh", "Chandigarh"),
                            ("Chhatisgarh", "Chhatisgarh"),
                            ("Dadar & Nagar Haveli", "Dadar & Nagar Haveli"),
                            ("Daman & Diu", "Daman & Diu"),
                            ("Delhi", "Delhi"),
                            ("Goa", "Goa"),
                            ("Gujarat", "Gujarat"),
                            ("Haryana", "Haryana"),
                            ("Himachal Pradesh", "Himachal Pradesh"),
                            ("Jammu & Kashmir", "Jammu & Kashmir"),
                            ("Jharkhand", "Jharkhand"),
                            ("Karnataka", "Karnataka"),
                            ("Kerala", "kerala"),
                            ("Lakshdweep", "Lakshdweep"),
                            ("Madhya Pradesh", "Madhya Pradesh"),
                            ("Mahrarstra", "Mahrarstra"),
                            ("Manipur", "Manipur"),
                            ("Meghalya", "Meghalya"),
                            ("Mizoram", "Mizoram"),
                            ("Nagaland", "Nagaland"),
                            ("Odisha", "Odisha"),
                            ("Punduchery", "Punduchery"),
                            ("Punjab", "Punjab"),
                            ("Rajsathan", "Rajsathan"),
                            ("Sikkim", "Sikkim"),
                            ("Tamil Nadu", "Tamil Nadu"),
                            ("Telengana", "Telengana"),
                            ("Tripura", "Tripura"),
                            ("Utter Pradesh", "Utter Pradesh"),
                            ("West Bengal", "West Bengal"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("selling_price", models.FloatField()),
                ("discount_price", models.FloatField()),
                ("description", models.TextField()),
                (
                    "brand",
                    models.CharField(
                        choices=[
                            ("M", "Mobile"),
                            ("L", "Laptop"),
                            ("TW", "Top Wear"),
                            ("BW", "Bottom Wear"),
                        ],
                        max_length=2,
                    ),
                ),
                ("product_image", models.ImageField(upload_to="Productimg")),
            ],
        ),
        migrations.CreateModel(
            name="OrderPlaced",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveBigIntegerField(default=1)),
                ("ordered_data", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Andaman & Nincobar Island", "Andaman & Nincobar Island"),
                            ("Andhra Pradesh", "Andhra Pradesh"),
                            ("Assam", "Assam"),
                            ("Bihar", "Bihar"),
                            ("Chandigarh", "Chandigarh"),
                            ("Chhatisgarh", "Chhatisgarh"),
                            ("Dadar & Nagar Haveli", "Dadar & Nagar Haveli"),
                            ("Daman & Diu", "Daman & Diu"),
                            ("Delhi", "Delhi"),
                            ("Goa", "Goa"),
                            ("Gujarat", "Gujarat"),
                            ("Haryana", "Haryana"),
                            ("Himachal Pradesh", "Himachal Pradesh"),
                            ("Jammu & Kashmir", "Jammu & Kashmir"),
                            ("Jharkhand", "Jharkhand"),
                            ("Karnataka", "Karnataka"),
                            ("Kerala", "kerala"),
                            ("Lakshdweep", "Lakshdweep"),
                            ("Madhya Pradesh", "Madhya Pradesh"),
                            ("Mahrarstra", "Mahrarstra"),
                            ("Manipur", "Manipur"),
                            ("Meghalya", "Meghalya"),
                            ("Mizoram", "Mizoram"),
                            ("Nagaland", "Nagaland"),
                            ("Odisha", "Odisha"),
                            ("Punduchery", "Punduchery"),
                            ("Punjab", "Punjab"),
                            ("Rajsathan", "Rajsathan"),
                            ("Sikkim", "Sikkim"),
                            ("Tamil Nadu", "Tamil Nadu"),
                            ("Telengana", "Telengana"),
                            ("Tripura", "Tripura"),
                            ("Utter Pradesh", "Utter Pradesh"),
                            ("West Bengal", "West Bengal"),
                        ],
                        default="Pending",
                        max_length=50,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.customer"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.product"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quanlity", models.PositiveBigIntegerField(default=1)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.product"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
