# Generated by Django 4.1.5 on 2024-05-18 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("M", "Mobile"),
                    ("L", "Laptop"),
                    ("TW", "Top Wear"),
                    ("BW", "Bottom Wear"),
                ],
                default="TW",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="brand",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(max_length=150),
        ),
        migrations.AlterField(
            model_name="product",
            name="discount_price",
            field=models.FloatField(max_length=102),
        ),
        migrations.AlterField(
            model_name="product",
            name="selling_price",
            field=models.FloatField(max_length=10),
        ),
    ]
